# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bdc0f70570802cdd7ab9a13ab12efd48071cc85b57ad796bba9d2d885cffc0cccfbb54e4aa971311ab930900236a2a3600507f8f3cb78bed1e5aa2baa1cf042

test:
  secret_key_base: 14199a2c625db8d9fc56d4ad853a4a4ecd8f330fdbceaa036dfc1310c1e95e3170185f6c7baeabc0dcf1bfa5e0ccb0df2a420ce896b1c9080d9aa27138b02b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
